global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # IoT Metrics Service
  - job_name: 'iot-metrics-service'
    static_configs:
      - targets: ['iot-metrics-service:8080']
    metrics_path: '/api/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 15s