apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-metrics-service
  namespace: iot-metrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-metrics-service
  template:
    metadata:
      labels:
        app: iot-metrics-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: iot-metrics-service
        image: iot-metrics-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: "redis.iot-metrics.svc.cluster.local:6379"
        resources:
          requests:
            cpu: "100m"      # 0.1 CPU ядра
            memory: "128Mi"
          limits:
            cpu: "500m"      # 0.5 CPU ядра
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5