apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-metrics-ingress
  namespace: iot-metrics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: iot-metrics.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: iot-metrics-service
            port:
              number: 8080